[package]
name = "loom_embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.1", features = ["luau-jit", "vendored", "serialize", "macros"] }
raylib = "5.0.2"
serde = { version = "1.0.216", features = ["derive"] }
